apiVersion: v1
kind: Service
metadata:
  name: {{ include "customnginx.fullname" . }}
  {{- with .Values.namespace.name }}
  namespace: {{ . }}
  {{- end }}
  labels:
    app: nginx
spec:
  type: {{ .Values.type }}
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.containerPort }}
      nodePort: {{ .Values.nodePort }}
